#!/bin/bash
### BEGIN INIT INFO
# Provides: android-raspbian-status
# Required-Start: $all
# Required-Stop: $local_fs $network $time $remote_fs $syslog avahi-daemon
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Daemon status at boot/shutdown
# Description: Raspbian for Android Status
### END INIT INFO

case "$1" in
start)

yes ' ' | sed 60q
IP=$(avahi-resolve -4 -n pihole.local | cut -f 2) ; (&>/dev/null avahi-publish -a -R $(hostname).local $IP &)
IP=$(avahi-resolve -4 -n pihole.local | cut -f 2) ; (&>/dev/null avahi-publish -a -R nextcloudpi.local $IP &)
DIST=$(cat /etc/*-release | egrep "PRETTY_NAME" | cut -d = -f 2 | tr -d '"')
ARCH=$(dpkg --print-architecture)
[[ "$ARCH" = "aarch64" ]] && ARCH="ARM64" || ARCH="ARM32"
printf "\n$DIST $ARCH on $(hostname)\n" > /etc/motd
cat /etc/motd
echo '_______________________________________________'
echo '                                               '
   pihole -v
   if [ -f /var/tmp/p4a ] ; then
      P4A=`cat /var/tmp/p4a`
      rm /var/tmp/p4a
      echo " "
      echo " IMPORTANT: RDP/SSH/Pi-hole admin password is"
      echo "            shown below ONCE, record it now!"
      echo " "
      echo "  --> $P4A <--"
      P4A="NOPE"
    else
     echo " "
     pihole status
  fi
echo '_______________________________________________'
echo
;;

stop)

yes ' ' | sed 50q
echo '_______________________________________________'
echo '                                               '
echo '     *** Container SHUTDOWN Initiated! ***     '
echo '_______________________________________________'
yes ' ' | sed 2q
;;

*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
