language: php
php:
  - 7
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=previewgenerator
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
  - . ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../server
  - ./occ check
  - ./occ status
  - ./occ app:list
  - ./occ app:enable $APP_NAME

script:
  - cd apps/$APP_NAME/

  # Test the app
  - sh -c "find . -name \*.php -exec php -l \"{}\" \;;"
  - cd ../../
  #- sh -c "./occ app:check-code $APP_NAME -c private -c strong-comparison;"
  #- sh -c "./occ app:check-code $APP_NAME -c deprecation;"
  - cd apps/$APP_NAME/

  # Run phpunit tests
  - cd tests/
  - sh -c "phpunit --configuration phpunit.xml"

after_success:
  - bash <(curl -s https://codecov.io/bash)
